spring:
  main:
    allow-bean-definition-overriding: true

  port: 8080
  application:
    name: 'PhoneSystem'

  session:
    store-type: 'jdbc'

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    type: "org.apache.tomcat.jdbc.pool.DataSource"

    tomcat:
      max-total: 50
      pool-prepared-statements: true
      max-wait: 5000
      max-active: 30
      max-idle: 10
      remove-abandoned-timeout: 60
      remove-abandoned-on-maintenance: true
      remove-abandoned-on-borrow: true

      # debug
      #log-abandoned: true
      #abandoned-usage-tracking: true


logging:
  level:
    org:
      springframework:
        security: "TRACE"
        web: "DEBUG"
        hibernate: "ERROR"

encryption:
  key: "weasf"
  salt: "wesafasdf"

templates:
  addphone: "addphone"
  login: "login"
  index: "index"
  register: "register"

page:
  max_page_size: 20

variables:
  list_of_phones: "phones"
