spring:
  port: 8080
  application:
    name: 'PhoneSystem'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

encryption:
  key: "weasf"
  salt: "wesafasdf"


test:
  url: "http://127.0.0.1:8080/"
