spring:
  port: 8080
  application:
    name: 'PhoneSystem'

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  datasource:
    url: 'jdbc:postgresql://127.0.0.1:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    tomcat:
      initial-size: 1
      max-wait: 10000
      max-active: 50
      test-on-borrow: true


logging:
  level:
    org:
      springframework:
        security: "TRACE"
        web: "DEBUG"
        hibernate: "ERROR"

encryption:
  key: "weasf"
  salt: "wesafasdf"

templates:
  addphone: "addphone"
  login: "login"
  index: "index"
  register: "register"

page:
  max_page_size: 20

variables:
  list_of_phones: "phones"
